### ISSUE TITLE
一个高度计算的问题。

### ISSUE THREAD

**Issue by weipeng02** [lijingcheng/JCTagListView#12]
当我第一个标签的内容过多的时候，前面有很大一部分的空白。第一张是正常的，第二张是内容过多的时候的问题。
![f763e76f-87de-4dab-8108-8fb26d94f6f9](https://cloud.githubusercontent.com/assets/17291586/24788051/0adaeb14-1b9e-11e7-8ce6-f66926d691f4.png)
![40c24ba6-2306-425e-a084-eb44b8f1b4c6](https://cloud.githubusercontent.com/assets/17291586/24788064/1434589e-1b9e-11e7-9ea7-2daf80ea72fa.png)

**Comment by lijingcheng** [comment]
内容过多的话就不算 tag 了，所以建议你 fork 后自己改改吧，大概思路就是：tag 中的 label 目前不支持多行，你让他支持多行后试试吧
