### ISSUE TITLE
数据变多的话计算就不精确了, 会遮住tagview

### ISSUE THREAD

**Issue by snaillovesmile** [lijingcheng/JCTagListView#16]

**Comment by lijingcheng** [comment]
是指标签很多超过一屏吗？还是指标签内显示文字过长？这两种情况目前都没考虑。

**Comment by lijingcheng** [comment]
@SnailLoveSmile 是指标签很多超过一屏吗？还是指标签内显示文字过长？这两种情况目前都没考虑。

**Comment by snaillovesmile** [comment]
demo 里cell数据, 如果子数组中多加写tag标签, 就会出行啊cell高度计算不准确导致, 有些标签看不到了

**Comment by lijingcheng** [comment]
@SnailLoveSmile 哦，下周有时间时我看一下，谢谢

**Comment by snaillovesmile** [comment]
嗯嗯, 辛苦了Li 3Q

**Comment by lijingcheng** [comment]
@SnailLoveSmile 最近事情比较多，这两天花时间对整个库做了较大更新，有时间时你再看下吧，应该是都改好了 :]

**Comment by snaillovesmile** [comment]
嗯嗯, 谢谢
