### ISSUE TITLE
pod install issue on 2.0.0

### ISSUE THREAD

**Issue by selmaster** [lijingcheng/JCTagListView#17]
I tried your new version pod updated with pod 'JCTagListView', '2.0.0' but not found 2.0.0 version:
_"CocoaPods could not find compatible versions. None of your spec sources contain a spec satisfying the dependency: 'JCTagListView (= 2.0.0)' "._

pod 'JCTagListView' only return latest version is 1.0.2. Please help.

**Comment by lijingcheng** [comment]
Try again after pod setup

**Comment by selmaster** [comment]
@lijingcheng It worked. I didn't try that step before. Thank a lot for your help.
