### ISSUE TITLE
Is this possible to center cells

### ISSUE THREAD

**Issue by premkumarmsc** [lijingcheng/JCTagListView#6]
Hi, 

Is this possible to center cells like Flipboard? Please help me.

**Comment by lijingcheng** [comment]
@premkumarmsc  hi, what's center cells? like the iPhone photo album?

**Comment by premkumarmsc** [comment]
No. like Flipboard app  interest selection.

_Cheers,_

PREMKUMAR.K
PROJECT MANAGER & HUMAN RIGHTS COUNCIL
MOBILE:+919750917456

**Comment by lijingcheng** [comment]
@premkumarmsc ok, i see, does not support,you can use UICollectionView and add UILabel in cell，and set the UILabel's border and backgroundColor

**Comment by premkumarmsc** [comment]
Okay Fine thanks.

_Cheers,_

PREMKUMAR.K
PROJECT MANAGER & HUMAN RIGHTS COUNCIL
MOBILE:+919750917456
